apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: devopsaks 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devopsaks 
    spec:
      containers:
        - name: devopsaks 
          image: mycontainerregisstry.azurecr.io/devopsaks
          ports:
          - containerPort: 8080